server:
  port: 8989

mybatis:
  # mapper.xml location Setting
  mapper-locations: mappers/**/*Mapper.xml  # alias Setting
  type-aliases-package: com.won.dourbest.seller.dto, com.won.dourbest.user.dto, com.won.dourbest.admin.account.dto, com.won.dourbest.common.dto, com.won.dourbest.main.model.dto
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@oracle.coffit.site:1521:XE
    username: C##DOURBEST
    password: DOURBEST
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\dev\fundingImg
  mvc:
    converters:
      preferred-json-mapper: gson
  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: ddj04323 #네이버 아이디
    password: H3FVS7HFTCDZ #네이버 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
          auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000
          ssl:
            #trust: smtp.naver.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면
